# Numpy

In [33]:
import numpy as np

In [10]:
array1=np.array([2,3,5,7,11,13,17,19,23,29,31])

In [14]:
array2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [18]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [15]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## - Numpy 특성

### array 차원

In [16]:
print(array1.shape,array2.shape)

(11,) (3, 4)


### array 요소 개수

In [17]:
print(array1.size, array2.size)

11 12


## - Numpy array 생성

### 1) 파이썬 리스트

In [20]:
array1=np.array([2,3,5,7,11,13,17,19,21])
print(array1)

[ 2  3  5  7 11 13 17 19 21]


### 2) 균일한 값

In [23]:
array1=np.full(6,7)
print(array1)

[7 7 7 7 7 7]


In [24]:
array1=np.zeros(6, dtype=int)
print(array1)

[0 0 0 0 0 0]


In [25]:
array1=np.ones(6, dtype=int)
print(array1)

[1 1 1 1 1 1]


### 3) 랜덤한 값

In [26]:
array1=np.random.random(6)
print(array1)

[0.43619935 0.93479092 0.39610496 0.49989725 0.73514384 0.09676044]


### 4) 연속된 값

In [27]:
array1=np.arange(6)
print(array1)

[0 1 2 3 4 5]


In [28]:
array1=np.arange(2,7)
print(array1)

[2 3 4 5 6]


In [29]:
array1=np.arange(3,17,3)
print(array1)

[ 3  6  9 12 15]


## - 인덱싱/슬라이싱

In [43]:
array1=np.array([2,3,5,7,11,13,17,19,23,29,31])

In [39]:
array1[[1,3,4]]

array([ 3,  7, 11])

In [42]:
array2=np.array([2,1,3])
array1[array2]

array([5, 3, 7])

In [46]:
array1[:7:2]

array([ 2,  5, 11, 17])

## - Numpy 기본 연산

In [47]:
array1=np.arange(10)
array2=np.arange(10,20)

In [49]:
print(array1,array2)

[0 1 2 3 4 5 6 7 8 9] [10 11 12 13 14 15 16 17 18 19]


In [50]:
array1*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [51]:
array1/2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [55]:
array1+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
array1-2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [56]:
array1+array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [57]:
array1*array2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

## - boolean 연산

In [58]:
array1=np.array([2,3,5,7,11,13,17,19,23,29,31])

In [59]:
array1>4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [60]:
array1%2==0

array([ True, False, False, False, False, False, False, False, False,
       False, False])

In [61]:
booleans=np.array([True, True, False, True, True, False, True, True, True, False, True])

In [62]:
np.where(booleans)

(array([ 0,  1,  3,  4,  6,  7,  8, 10], dtype=int64),)

In [66]:
filter=np.where(array1>4)
filter

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [68]:
array1[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

## 기본 통계

In [75]:
array1=np.array([14,6,13,21,23,31,9,5])

In [70]:
print(array1.max(),array1.min())

31 5


In [72]:
print(array1.mean())

15.25


In [73]:
array1=np.array([8,12,9,15,16])
array2=np.array([14,6,13,21,23,31,9,5])

In [74]:
print(np.median(array1),np.median(array2))

12.0 13.5


In [77]:
print(array1.std(),array1.var())

8.496322733983215 72.1875
